package it.unimib.disco.essere.core;


import java.util.ArrayList;

import it.unimib.disco.essere.functionalities.Predictor;
import it.unimib.disco.essere.load.Loader;
import weka.classifiers.Classifier;

/**
* Class for execute all the operation concerning the prediction
* <br/>
* */

public class PredictionHandler extends Handler {
	
	/** the list generated by the concrete Loader used, it contain: 
	 * path of the dataset, labels, path of the serialized classifiers
	 * */
	private ArrayList<String> paths;
	
	/**
	 * Default Constructor for the prediction through command line
	 * */
	public PredictionHandler(){
		this.configuration = null;
	}
	
	/**
	 * Constructor for the prediction throws configuration file
	 * @param path the path of the configuration file 
	 * @throws Exception 
	 * */
	public PredictionHandler(Loader config, String path) throws Exception{
		this.configuration = config;
		paths =  configuration.loadForPrediction(path);
	}
	
	/**
	 * Perform the prediction if the class was instantiated with the configuration file
	 * */
	public void predict() throws Exception{
		
		if(configuration == null){
			throw new NullPointerException("Wrong contructor used for create the istances");
		}
		
		String	pathDataset =  paths.get(0);
		paths.remove(0);
		
		String	labels =  paths.get(0);
		paths.remove(0);

		for(String path: paths){
			Classifier c = null;
			try {
				c = serializer.read(path);
			}catch(Exception e){
				printErrorPred();
			}

			predictAndPrint(pathDataset, c, labels);
		}
	}
	
	/**
	 * Perform the prediction if the class was instantiated through command line
	 * 
	 * @param path1  the path of the dataset
	 * @param path2  the path of the serialized file
	 * @param labels the labels of the attribute to be predicted 
	 * */
	public void predict(String path1, String path2, String labels) throws Exception{
		String pathDataset = path1;
		String pathSerialized = path2;
		Classifier c = null;
		try{
			c = serializer.read(pathSerialized);
		}catch(Exception e1){
			String temp = pathDataset;
			pathDataset = pathSerialized;
			pathSerialized = temp;
			try {
				c = serializer.read(pathSerialized);
			} catch(Exception e){
				printErrorPred();
			} 
		}

		predictAndPrint(pathDataset, c, labels);
	}
	
	/**
	 * Perform the prediction and save the result in a new file in the same folder of the original dataset
	 * 
	 * @param pathDataset  the path of the dataset
	 * @param c            the classifier used to predict the value
	 * @param labels       the labels of the attribute to be predicted 
	 * */
	private void predictAndPrint(String pathDataset, Classifier c, String labels) throws Exception {
		//predict
		DatasetHandler dataset = new DatasetHandler(pathDataset);
		Predictor predictor = new Predictor(dataset.getDataset());
		DatasetHandler datasetPredicted = null;
		datasetPredicted = predictor.makePredicitions(c, labels);

		//print
		String directory = pathDataset.substring(0, pathDataset.lastIndexOf('/')+1);
		String name = pathDataset.substring(pathDataset.lastIndexOf('/') + 1);
		String nameClassifier = c.getClass().getName();
		nameClassifier = nameClassifier.substring(nameClassifier.lastIndexOf('.')).replace(".", "");

		String path = directory + "Predicted_" + nameClassifier + "_" + name;

		//save
		datasetPredicted.toCSV(path);
		System.out.println("The predict model is saved in: " + path);
	}

	/**
	 * Print out the error message in case the serialized file is incorrect
	 * */
	private void printErrorPred() throws Exception {
		LOGGER.severe("------------------------------------------------------------------\n"
		+"ERROR : the serialized file is incorrect, please check the path \n"
		+"	and make sure that the file is a .model\n" 
		+"------------------------------------------------------------------");
		throw new Exception();
	}

}
